[package]
name = "tadeusz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.10.0"
anyhow = "1.0.58"
rosc = "0.8.1"
wav = "1.0.0"